#!/bin/bash

e=0

vcom constants.vhd && (echo Success...) || (((e++)))
vcom iv.vhd && (echo Success...) || (((e++)))
vcom nd2.vhd && (echo Success...) || (((e++)))
vcom mux21_generic.vhd && (echo Success...) || (((e++)))
vcom fa.vhd && (echo Success...) || (((e++)))
vcom rca.vhd && (echo Success...) || (((e++)))
vcom carry_select.vhd && (echo Success...) || (((e++)))
vcom sum_generator.vhd && (echo Success...) || (((e++)))
vcom tb_sum_generator.vhd && (echo Success...) || (((e++)))
vcom pg_network.vhd && (echo Success...) || (((e++)))
vcom g_block.vhd && (echo Success...) || (((e++)))
vcom pg_block.vhd && (echo Success...) || (((e++)))
vcom carry_generator.vhd && (echo Success...) || (((e++)))
vcom tb_carry_generator.vhd && (echo Success...) || (((e++)))

echo Done.
echo $e errors.